name: Deploy pull start

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Git pull
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t jfd .
      - name: Run container
        run: docker run -d -p 80:8080 --name jfd --rm jfd
