name: Docker Image CI

on: [workflow_dispatch]

jobs:

  build:

    runs-on: self-hosted

    steps:
      -
        name: Build the Docker image
        run: docker build -t jfd .
      -
        name: Run container
        run: docker run -d -p 80:8080 --name jfd --rm jfd
